name: Test React App

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'  # 使用您想要的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm start

    - name: Report results
      run: echo "Testing completed!"
